stages:
  reorganize_locations:
    cmd: >-
      uv run python scripts/data/reorganize_locations.py
      --input-dir data/01_raw/locations
      --output-dir data/02_processed/locations
      --config-dir data/02_processed/config
    deps:
      - scripts/data/reorganize_locations.py
      - data/01_raw/locations
      - data/02_processed/config/naryn/individuals.yaml
      - data/02_processed/config/naryn/mappings.yaml
      - data/02_processed/config/sarychat/individuals.yaml
      - data/02_processed/config/sarychat/mappings.yaml
    outs:
      - data/02_processed/locations
    desc: "Reorganize snow leopard images from raw data into processed structure using canonical individual configs"

  grounding_dino_detection:
    cmd: >-
      uv run python scripts/models/grounding_dino.py
      --input-dir data/02_processed/locations
      --output-dir data/05_model_output/grounding_dino
      --text-prompt "a snow leopard."
      --model-id IDEA-Research/grounding-dino-base
      --box-threshold 0.30
      --text-threshold 0.20
    deps:
      - scripts/models/grounding_dino.py
      - data/02_processed/locations
    outs:
      - data/05_model_output/grounding_dino
    desc: "Detect snow leopards in images using GroundingDINO zero-shot object detection"

  sam_hq_segmentation:
    cmd: >-
      uv run python scripts/models/sam_hq.py
      --input-dir data/02_processed/locations
      --predictions-dir data/05_model_output/grounding_dino/predictions
      --output-dir data/05_model_output/sam_hq
      --checkpoint data/04_models/SAM_HQ/sam_hq_vit_l.pth
      --model-type vit_l
    deps:
      - scripts/models/sam_hq.py
      - data/02_processed/locations
      - data/05_model_output/grounding_dino
      - data/04_models/SAM_HQ/sam_hq_vit_l.pth
    outs:
      - data/05_model_output/sam_hq
    desc: "Generate high-quality segmentation masks using SAM HQ vit_l (Large) with GroundingDINO bounding boxes as prompts"

  crop_masks:
    cmd: >-
      uv run python scripts/data/crop_leopard_masks.py
      --sam-output-dir data/05_model_output/sam_hq
      --output-dir data/02_processed/cropped/leopards
      --padding 10
    deps:
      - scripts/data/crop_leopard_masks.py
      - data/05_model_output/sam_hq
    outs:
      - data/02_processed/cropped/leopards
    desc: "Crop individual snow leopards from images using SAM HQ masks with black background for downstream processing"

  build_catalog:
    cmd: >-
      uv run python scripts/catalog/build_catalog_from_selection.py
      --selection-file data/08_catalog/v1.0/selection.yaml
      --catalog-dir data/08_catalog/v1.0/database &&
      uv run python scripts/catalog/extract_catalog_features.py
      --catalog-dir data/08_catalog/v1.0/database
      --extractor sift
      --max-keypoints 2048 &&
      uv run python scripts/catalog/generate_catalog_metadata.py
      --catalog-dir data/08_catalog/v1.0
      --catalog-version 1.0.0
    deps:
      - scripts/catalog/build_catalog_from_selection.py
      - scripts/catalog/extract_catalog_features.py
      - scripts/catalog/generate_catalog_metadata.py
      - data/02_processed/cropped/leopards
      - data/08_catalog/v1.0/selection.yaml
    outs:
      - data/08_catalog/v1.0/database
      - data/08_catalog/v1.0/catalog_index.yaml
    desc: "Build leopard identification catalog from selection: copy images, extract SIFT features, generate metadata"
