stages:
  reorganize_locations:
    cmd: >-
      uv run python scripts/data/reorganize_locations.py
      --input-dir data/01_raw/locations
      --output-dir data/02_processed/locations
      --config-dir data/02_processed/config
    deps:
      - scripts/data/reorganize_locations.py
      - data/01_raw/locations
      - data/02_processed/config/naryn/individuals.yaml
      - data/02_processed/config/naryn/mappings.yaml
      - data/02_processed/config/sarychat/individuals.yaml
      - data/02_processed/config/sarychat/mappings.yaml
    outs:
      - data/02_processed/locations
    desc: "Reorganize snow leopard images from raw data into processed structure using canonical individual configs"

  grounding_dino_detection:
    cmd: >-
      uv run python scripts/models/grounding_dino.py
      --input-dir data/02_processed/locations
      --output-dir data/05_model_output/grounding_dino
      --text-prompt "a snow leopard."
      --model-id IDEA-Research/grounding-dino-base
      --box-threshold 0.30
      --text-threshold 0.20
    deps:
      - scripts/models/grounding_dino.py
      - data/02_processed/locations
    outs:
      - data/05_model_output/grounding_dino
    desc: "Detect snow leopards in images using GroundingDINO zero-shot object detection"
